# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "jeffs_cursed_walking_structures:mutated_spawner_placer",
    "alexsmobs:snow_leopard",
    "jeffs_cursed_walking_structures:bunker_spawner_placer",
    "apocalypsenow:soldiers_02",
    "alexsmobs:endergrade",
    "jurassicreborn:majungasaurus",
    "minecraft:horse",
    "minecraft:llama",
    "jurassicreborn:vectipelta",
    "jurassicreborn:corythosaurus",
    "alexsmobs:skreecher",
    "minecraft:tadpole",
    "apocalypsenow:hunter",
    "alexsmobs:hammerhead_shark",
    "alexsmobs:grizzly_bear",
    "alexsmobs:murmur_head",
    "max_armory:east_soldier",
    "jurassicreborn:alligatorgar",
    "minecraft:mooshroom",
    "minecraft:axolotl",
    "jurassicreborn:spinosaurus",
    "alexsmobs:gorilla",
    "alexsmobs:cosmic_cod",
    "extinction:soldier_clicker",
    "jurassicreborn:orthoceras",
    "alexsmobs:kangaroo",
    "ecologics:coconut_crab",
    "extinction:patient_zero_i",
    "bloomingnature:termite",
    "mutantszombies:mutant_brute",
    "alexsmobs:hummingbird",
    "mutantmonsters:mutant_zombie",
    "extinction:infected_hazmat",
    "dreamcaslib:seismic_wave",
    "jurassicreborn:pteranodon",
    "alexsmobs:crow",
    "apocalypsenow:soldiers",
    "alexsmobs:guster",
    "bloomingnature:wandering_gardener",
    "jurassicreborn:compsognathus",
    "jurassicreborn:giganotosaurus",
    "minecraft:chicken",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "alexsmobs:emu",
    "jurassicreborn:indominus",
    "superbwarfare:senpai",
    "alexsmobs:flutter",
    "minecraft:hoglin",
    "jurassicreborn:proceratosaurus",
    "jurassicreborn:microraptor",
    "jurassicreborn:leaellynasaura",
    "minecraft:zombified_piglin",
    "dweller_dweller:ominous_presence",
    "minecraft:sheep",
    "alexsmobs:bone_serpent_part",
    "alexsmobs:raccoon",
    "minecraft:ravager",
    "alexsmobs:bone_serpent",
    "jurassicreborn:brachiosaurus",
    "jurassicreborn:dodo",
    "jurassicreborn:dunkleosteus",
    "extinction:boomer",
    "alexsmobs:mudskipper",
    "jurassicreborn:dimetrodon",
    "mutantszombies:zombie_brute",
    "alexsmobs:crimson_mosquito",
    "jurassicreborn:paraceratherium",
    "jurassicreborn:edmontosaurus",
    "decoration_delight:stool_entity",
    "alexsmobs:jerboa",
    "jurassicreborn:hyaenodon",
    "alexsmobs:comb_jelly",
    "apocalypsenow:runner_39",
    "apocalypsenow:runner_38",
    "apocalypsenow:runner_37",
    "railways:conductor",
    "apocalypsenow:runner_36",
    "apocalypsenow:runner_35",
    "apocalypsenow:runner_34",
    "apocalypsenow:cockroach",
    "extinction:stalker_ii",
    "jurassicreborn:titanis",
    "jurassicreborn:lambeosaurus",
    "alexsmobs:enderiophage",
    "apocalypsenow:runner_49",
    "apocalypsenow:runner_48",
    "alexsmobs:sunbird",
    "apocalypsenow:runner_43",
    "apocalypsenow:runner_42",
    "apocalypsenow:runner_41",
    "apocalypsenow:runner_40",
    "apocalypsenow:runner_47",
    "apocalypsenow:runner_46",
    "apocalypsenow:runner_45",
    "apocalypsenow:runner_44",
    "minecraft:cat",
    "apocalypsenow:runner_50",
    "jurassicreborn:styracosaurus",
    "minecraft:tropical_fish",
    "jurassicreborn:mawsonia",
    "jurassicreborn:smilodon",
    "apocalypsenow:runner_54",
    "apocalypsenow:runner_53",
    "apocalypsenow:runner_52",
    "minecraft:zombie_villager",
    "apocalypsenow:runner_51",
    "apocalypsenow:runner_57",
    "apocalypsenow:runner_56",
    "apocalypsenow:runner_55",
    "alexsmobs:froststalker",
    "minecraft:giant",
    "alexsmobs:lobster",
    "alexsmobs:seagull",
    "jurassicreborn:protoceratops",
    "jeffs_cursed_walking_structures:hazmat_spawner_placer",
    "minecraft:husk",
    "jurassicreborn:goat",
    "extinction:infected_riot_gear",
    "minecraft:donkey",
    "jeffs_cursed_walking_structures:nomorewaterlogging",
    "jurassicreborn:segisaurus",
    "mutantmonsters:mutant_skeleton",
    "jurassicreborn:velociraptordelta",
    "jurassicreborn:cameroceras",
    "minecraft:piglin_brute",
    "extinction:traveler",
    "superbwarfare:target",
    "apocalypsenow:military_medic",
    "jurassicreborn:megapiranha",
    "alexsmobs:frilled_shark",
    "mutantszombies:crawler",
    "alexsmobs:bald_eagle",
    "extinction:soldier",
    "alexsmobs:blobfish",
    "ecologics:squirrel",
    "jurassicreborn:guanlong",
    "alexsmobs:void_worm",
    "jurassicreborn:spinoraptor",
    "minecraft:parrot",
    "max_armory:esat_officer",
    "alexsmobs:centipede_head",
    "alexsmobs:banana_slug",
    "mutantmonsters:mutant_creeper",
    "jurassicreborn:carnotaurus",
    "alexsmobs:bunfungus",
    "minecraft:mule",
    "minecraft:vindicator",
    "alexsmobs:flying_fish",
    "mutantszombies:blister_zombie",
    "jurassicreborn:ludodactylus",
    "jurassicreborn:othnielia",
    "jeffs_cursed_walking_structures:driller",
    "jurassicreborn:carcharodontosaurus",
    "jeffsgibbing:ribs",
    "apocalypsenow:walker_29",
    "apocalypsenow:walker_28",
    "apocalypsenow:walker_27",
    "apocalypsenow:walker_26",
    "jurassicreborn:raphusrex",
    "apocalypsenow:walker_25",
    "apocalypsenow:walker_24",
    "apocalypsenow:walker_23",
    "apocalypsenow:walker_22",
    "apocalypsenow:walker_21",
    "jurassicreborn:quetzal",
    "apocalypsenow:walker_20",
    "jurassicreborn:sinoceratops",
    "alexsmobs:terrapin",
    "minecraft:pig",
    "alexsmobs:alligator_snapping_turtle",
    "apocalypsenow:walker_33",
    "apocalypsenow:walker_32",
    "apocalypsenow:walker_31",
    "jurassicreborn:beelzebufo",
    "apocalypsenow:walker_30",
    "minecraft:cod",
    "jeffsgibbing:asmd_combo",
    "alexsmobs:platypus",
    "extinction:hunter",
    "minecraft:cow",
    "jurassicreborn:rugops",
    "alexsmobs:rocky_roller",
    "jurassicreborn:arsinoitherium",
    "alexsmobs:soul_vulture",
    "jurassicreborn:camarasaurus",
    "alexsmobs:blue_jay",
    "jurassicreborn:mosasaurus",
    "minecraft:salmon",
    "apocalypsenow:walker_19",
    "jurassicreborn:asteroceras",
    "apocalypsenow:walker_18",
    "apocalypsenow:walker_17",
    "apocalypsenow:walker_16",
    "apocalypsenow:walker_15",
    "jurassicreborn:coelurus",
    "extinction:parasite",
    "apocalypsenow:walker_14",
    "apocalypsenow:walker_13",
    "apocalypsenow:walker_12",
    "apocalypsenow:walker_11",
    "alexsmobs:anteater",
    "apocalypsenow:walker_10",
    "alexsmobs:rain_frog",
    "minecraft:rabbit",
    "jurassicreborn:velociraptorblue",
    "minecraft:pillager",
    "minecraft:zoglin",
    "jurassicreborn:moganopterus",
    "jurassicreborn:velociraptor",
    "alexsmobs:leafcutter_ant",
    "jurassicreborn:metriacanthosaurus",
    "extinction:fallen_survivor",
    "apocalypsenow:military_02",
    "apocalypsenow:military_01",
    "alexsmobs:gazelle",
    "minecraft:sniffer",
    "jurassicreborn:elasmotherium",
    "jurassicreborn:crab",
    "apocalypsenow:cannibal",
    "jurassicreborn:hypsilophodon",
    "jurassicreborn:megalodon",
    "jurassicreborn:indoraptor",
    "jurassicreborn:achillobator",
    "jurassicreborn:alvarezsaurus",
    "alexsmobs:seal",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "jurassicreborn:mussaurus",
    "minecraft:trader_llama",
    "jurassicreborn:kairuku",
    "alexsmobs:maned_wolf",
    "mutantszombies:split_head_zombie",
    "extinction:infected_police",
    "jurassicreborn:pachycephalosaurus",
    "minecraft:dolphin",
    "apocalypsenow:rat",
    "alexsmobs:gelada_monkey",
    "alexsmobs:dropbear",
    "jurassicreborn:calymene",
    "alexsmobs:tiger",
    "extinction:runner",
    "jurassicreborn:postosuchus",
    "jurassicreborn:deinosuchus",
    "jurassicreborn:mamenchisaurus",
    "minecraft:bee",
    "jurassicreborn:diplodocus",
    "alexsmobs:devils_hole_pupfish",
    "minecraft:illusioner",
    "jeffsgibbing:gib_head_entity",
    "alexsmobs:bison",
    "jurassicreborn:dreadnoughtus",
    "minecraft:drowned",
    "jeffsgibbing:gib_leg_entity",
    "alexsmobs:tusklin",
    "apocalypsenow:horde_2",
    "apocalypsenow:horde_3",
    "apocalypsenow:horde_4",
    "alexsmobs:underminer",
    "apocalypsenow:horde_5",
    "apocalypsenow:horde_1",
    "minecraft:wandering_trader",
    "extinction:patient_zero",
    "jurassicreborn:crassigyrinus",
    "jurassicreborn:mammoth",
    "hordes:drowned_player",
    "jurassicreborn:coelacanth",
    "jurassicreborn:tylosaurus",
    "minecraft:pufferfish",
    "minecraft:fox",
    "jurassicreborn:zhenyuanopterus",
    "immersiveengineering:bulwark",
    "alexsmobs:warped_toad",
    "immersiveengineering:fusilier",
    "alexsmobs:cockroach",
    "jurassicreborn:troodon",
    "apocalypsenow:looter_3",
    "extinction:mercenary",
    "apocalypsenow:looter_4",
    "apocalypsenow:looter_5",
    "apocalypsenow:looter_1",
    "apocalypsenow:looter_2",
    "jurassicreborn:allosaurus",
    "alexsmobs:capuchin_monkey",
    "hordes:husk_player",
    "apocalypsenow:walker_3",
    "minecraft:polar_bear",
    "apocalypsenow:walker_2",
    "apocalypsenow:walker_5",
    "apocalypsenow:walker_4",
    "apocalypsenow:walker_1",
    "minecraft:turtle",
    "apocalypsenow:walker_7",
    "apocalypsenow:walker_6",
    "apocalypsenow:walker_9",
    "apocalypsenow:walker_8",
    "jurassicreborn:velociraptorecho",
    "alexsmobs:rattlesnake",
    "jurassicreborn:perisphinctes",
    "jurassicreborn:cearadactylus",
    "jeffsgibbing:villager_ash",
    "jeffsgibbing:skelington",
    "extinction:goon",
    "jurassicreborn:patagotitan",
    "alexsmobs:potoo",
    "alexsmobs:fly",
    "alexsmobs:straddler",
    "alexsmobs:sea_bear",
    "dweller_dweller:dweller_dweller",
    "jurassicreborn:baryonyx",
    "jurassicreborn:chasmosaurus",
    "alexsmobs:sugar_glider",
    "jurassicreborn:livyatan",
    "jurassicreborn:chilesaurus",
    "alexsmobs:orca",
    "extinction:infected_mutated",
    "minecraft:bat",
    "alexsmobs:cosmaw",
    "jeffsgibbing:ash",
    "apocalypsenow:crawler_3",
    "apocalypsenow:survivor_10",
    "apocalypsenow:crawler_2",
    "apocalypsenow:crawler_4",
    "apocalypsenow:crawler_1",
    "alexsmobs:skunk",
    "jurassicreborn:velociraptorcharlie",
    "jurassicreborn:ceratosaurus",
    "alexsmobs:tasmanian_devil",
    "alexsmobs:stradpole",
    "ecologics:penguin",
    "minecraft:panda",
    "jeffs_cursed_walking_structures:warehouse_spawner_placer",
    "alexsmobs:moose",
    "jurassicreborn:nigersaurus",
    "alexsmobs:shoebill",
    "alexsmobs:farseer",
    "jurassicreborn:stegosaurus",
    "alexsmobs:warped_mosco",
    "immersiveengineering:commando",
    "hordes:zombie_player",
    "jurassicreborn:leptictidium",
    "jurassicreborn:gallimimus",
    "jeffsgibbing:flesh_3",
    "jeffsgibbing:flesh_2",
    "jurassicreborn:tyrannosaurus",
    "alexsmobs:komodo_dragon",
    "jurassicreborn:ornithomimus",
    "alexsmobs:crocodile",
    "jeffs_cursed_walking_structures:spawnpoint_entity",
    "alexsmobs:triops",
    "alexsmobs:rhinoceros",
    "jurassicreborn:tropeognathus",
    "alexsmobs:mimicube",
    "dreamcaslib:impact_wave",
    "jurassicreborn:maiasaura",
    "jeffsgibbing:flesh_entity",
    "minecraft:frog",
    "warrior:warrior",
    "jurassicreborn:suchomimus",
    "jurassicreborn:ankylosaurus",
    "alexsmobs:mimic_octopus",
    "alexsmobs:void_worm_part",
    "jurassicreborn:therizinosaurus",
    "minecraft:evoker",
    "jurassicreborn:dimorphodon",
    "alexsmobs:tarantula_hawk",
    "alexsmobs:cachalot_whale",
    "jurassicreborn:triceratops",
    "jurassicreborn:titanites",
    "alexsmobs:anaconda",
    "extinction:infected_bear",
    "minecraft:goat",
    "jurassicreborn:parasaurolophus",
    "mutantmonsters:mutant_enderman",
    "alexsmobs:mantis_shrimp",
    "jurassicreborn:deinotherium",
    "mutantmonsters:spider_pig",
    "apocalypsenow:survivor_5",
    "apocalypsenow:survivor_4",
    "apocalypsenow:survivor_3",
    "apocalypsenow:survivor_2",
    "apocalypsenow:survivor_1",
    "alexsmobs:toucan",
    "apocalypsenow:survivor_9",
    "apocalypsenow:survivor_8",
    "apocalypsenow:survivor_7",
    "apocalypsenow:survivor_6",
    "jurassicreborn:herrerasaurus",
    "jurassicreborn:ankylodocus",
    "jurassicreborn:apatosaurus",
    "extinction:stalker",
    "tacz_npc:bandit",
    "jurassicreborn:oviraptor",
    "alexsmobs:murmur",
    "mutantszombies:rotten_mutant",
    "alexsmobs:mungus",
    "alexsmobs:caiman",
    "alexsmobs:spectre",
    "jurassicreborn:megatherium",
    "alexsmobs:catfish",
    "mutantmonsters:endersoul_clone",
    "minecraft:piglin",
    "mutantszombies:spitter",
    "alexsmobs:skelewag",
    "jurassicreborn:dilophosaurus",
    "jurassicreborn:parapuzosia",
    "extinction:infected_soldier",
    "jurassicreborn:diplocaulus",
    "alexsmobs:elephant",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "jurassicreborn:endoceras",
    "jurassicreborn:shark",
    "superbwarfare:dps_generator",
    "jeffs_cursed_walking_structures:soldier_spawner_placer",
    "minecraft:ocelot",
    "jeffsgibbing:bone_entity",
    "minecraft:wolf",
    "extinction:runner_ii",
    "jurassicreborn:microceratus"
]
