#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Feb 26 18:26:49 IST 2026
colorSpace=ADOBE_RGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.3.zip
enableShaders=false
