#KubeJS Dev Properties
#Sun Mar 01 23:24:57 GMT 2026
alwaysCaptureErrors=false
dataPackOutput=false
debugInfo=false
logAddedRecipes=false
logErroringRecipes=true
logGeneratedData=false
logInvalidRecipeHandlers=true
logModifiedRecipes=false
logRemovedRecipes=false
logSkippedPlugins=true
logSkippedRecipes=false
logSkippedTags=false
strictTags=false
